-- Utiliser le rôle admin
USE ROLE ACCOUNTADMIN;

-- Créer le rôle `transform`
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Créer la warehouse par défaut
CREATE WAREHOUSE IF NOT EXISTS CHNAGE_ME_WH
    WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

GRANT OPERATE ON WAREHOUSE CHNAGE_ME_WH TO ROLE TRANSFORM;

-- Créer l'utilisateur DBT et lui assigner le rôle
CREATE USER IF NOT EXISTS dbt_taxi
  PASSWORD='MOT_DE_PASSE'
  LOGIN_NAME='DBT_LOGIN'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='CHNAGE_ME_WH'
  DEFAULT_ROLE='TRANSFORM'
  DEFAULT_NAMESPACE='CHNAGE_ME_DB.RAW'
  COMMENT='Utilisateur DBT pour la transformation des données';

GRANT ROLE TRANSFORM to USER dbt_taxi;

-- Création de la BDD
CREATE DATABASE IF NOT EXISTS CHNAGE_ME_DB;
CREATE SCHEMA IF NOT EXISTS CHNAGE_ME_DB.RAW;

-- Mise en place des permissions pour le rôle `transform`
GRANT ALL ON WAREHOUSE CHNAGE_ME_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE CHNAGE_ME_DB TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE CHNAGE_ME_DB TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE CHNAGE_ME_DB TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA CHNAGE_ME_DB.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA CHNAGE_ME_DB.RAW TO ROLE TRANSFORM;
-- GRANT ALL ON ALL TABLES IN SCHEMA CHNAGE_ME_DB.STAGING TO ROLE TRANSFORM;
-- GRANT ALL ON FUTURE TABLES IN SCHEMA CHNAGE_ME_DB.STAGING TO ROLE TRANSFORM;
-- GRANT ALL ON ALL TABLES IN SCHEMA CHNAGE_ME_DB.FINAL TO ROLE TRANSFORM;
-- GRANT ALL ON FUTURE TABLES IN SCHEMA CHNAGE_ME_DB.FINAL TO ROLE TRANSFORM;

SHOW GRANTS ON WAREHOUSE CHNAGE_ME_WH;